# Generated by Django 4.0.2 on 2022-02-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='genre',
            field=models.CharField(choices=[('IT', 'IT'), ('Accountant', 'Accountant'), ('Everyday', 'Everyday'), ('Eye', 'Eye')], default='Everyday', max_length=100),
        ),
        migrations.AddField(
            model_name='topic',
            name='nice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_text',
            field=models.CharField(default='', max_length=300),
        ),
    ]
