# Generated by Django 4.0.2 on 2022-02-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_topic_genre_topic_nice_topic_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_text',
            field=models.TextField(default=''),
        ),
    ]
