# Generated by Django 4.0.2 on 2022-03-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_topic_topic_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='genre',
            field=models.CharField(choices=[('IT', 'IT'), ('Accountant', 'Accountant'), ('Everyday', 'Everyday'), ('Eye', 'Eye'), ('ハリネズミ', 'ハリネズミ')], default='Everyday', max_length=100),
        ),
    ]
